FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app 

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps 
COPY packages ./packages 

# Installing dependencies 
RUN npm install 

# Adding script to global package.json 
RUN npm run db:prisma-generate 

# To Build all the Contents inside Apps
RUN npm run build 

# CMD cd ./apps/user-app && npm run start
#WORKDIR /usr/src/app/apps/user-app
#CMD npm run start

CMD ["npm", "run", "start-user-app"]



